# 项目相关配置
personal:
  # 名称
  name: sk
  # 版本
  version: 1.0.0
  # 年份
  timeYear: 2024
  # 文件存放路径
  path: D:/personal/upload
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
  #文件访问前缀
  prefix: prefix/

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8099
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
      exposure:
        #开启全部监控，当然也可以配置需要开启的监控，如： management.endpoints.web.exposure.include=beans,trace
        include: '*'
        #启用单独的url地址来监控 Spring Boot 应用，默认的路径是 /actuator/* ，如果开启此配置，重启后再次访问路径就会变成 /manage/*
     #base-path: /monitor
  endpoint:
    health:
      #开启显示全部细节。默认情况下, /actuator/health 是公开的，并且不显示细节。
      show-details: always
    shutdown:
      #启用接口关闭 Spring Boot
      enabled: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# 日志配置
logging:
  level:
    com.person: debug
    org.springframework: debug

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.person.**.domain,com.person.**.query
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml


